### ISSUE TITLE
`parse*` functions frequently have ambiguity errors on `e`

### ISSUE THREAD

**Issue by tysonzero** [mrkkrp/megaparsec#354] opened 2019-05-14 20:53 UTC
Most of my use cases have been fairly small one off parses that are too complex for basic `Data.Text` functions, but not complex enough to deserve a series of top level parsers with type signatures. I have also not needed to do any fancy error handling.

Because of all this pretty much every time I call `parse` or `parseMaybe` I have an ambiguity error on the `e` type variable, `TypeApplications` make it not too bad to deal with but I figured I would bring it up.

Since `parseMaybe` throws away `e` anyway, would it be worthwhile to restrict the type of `parseMaybe` to `Stream s => Parsec () s a -> s -> Maybe a` to maximize it's utility for quick on-the-fly parsers?

**Comment by mitchellwrosen** [comment] 2019-05-14 21:01
That'd prevent you from passing a parser that does not leave `e` polymorphic.

**Comment by tysonzero** [comment] 2019-05-14 21:06
Yeah I know that functions that leave `e` polymorphic are of course necessary, but for `parseMaybe` I have a feeling that more parsers leave `e` polymorphic then not, since if you are using fancy errors you probably aren't using `parseMaybe`. I could be wrong but that is my assumption.

One reason I bring the issue up is that it has been the main "regression" moving from Parsec to Megaparsec, as functions that previously type checked using Parsec's `parse` function now throw an ambiguity error.

**Comment by mitchellwrosen** [comment] 2019-05-14 21:15
Gotcha. My 2c: _if_ `parseMaybe` forced `e ~ ()`, and I had a "real" parser on hand that I just wanted to run down to a `Maybe` for whatever reason, I'd be kind of annoyed having to hunt around the haddocks for some

```
(e -> e') -> Parsec e s a -> Parsec e' s a
```

function. The convenience of `parseMaybe` would just completely vanish. OTOH, the status quo is that GHC will give you an ambiguous type variable error, which I immediately know how to solve. But I do see your point :)

**Comment by tysonzero** [comment] 2019-05-14 21:35
Maybe a `quickParse` or `parseSimple` or some other function could work, while leaving `parseMaybe` alone for quickly parsing "real" parsers, rather than for quickly parsing quick parsers (my use case).

An example of my use case is something like `parseMaybe (FooBar <$ "/foo/" <*> decimal <* "/bar/" <*> many letterChar) url` if that helps at all.

**Comment by mrkkrp** [comment] 2019-05-15 22:24
First of all, it should be `Void` instead of `()`. Second, it's not a problem to fix the type manually. There are more scary things in software development than this ;)

I'd rather avoid proliferation of parser-running functions. We already have enough. I think that when you have many ways to do X (e.g. run parser), it's just more confusing for people who are new to the library. 

This is my opinion, and since the issue is sort of a matter of opinions, I'm going to close it.

**Closed by mrkkrp** 2019-05-15 22:24 UTC

**Comment by tysonzero** [comment] 2019-05-16 06:43
I mean `Void` is enforcing that there are no fancy errors at all, `()` is saying that you can use them but you aren't allowed to put an interesting payload in them. I'd say it's subjective which one is better to use. Regardless it's only going to be used by people with parsers polymorphic in `e` so it doesn't matter.

I would say it's pretty annoying to do manually, at least when you are dealing with inline parsers. It basically means that the only clean-ish way to do inline parsing is by using TypeApplications, which is a significant regression from Parsec.

I suppose it depends a bit on the desired use case for megaparsec, as my use case of lots of small parsers might just be sufficiently niche to not be worth prioritizing.

**Comment by mrkkrp** [comment] 2019-05-16 08:13
> I mean Void is enforcing that there are no fancy errors at all, () is saying that you can use them but you aren't allowed to put an interesting payload in them

Why would you use them without interesting payload? To clarify: you can have what is called in the library "trivial errors" even with `Void`.

**Comment by tysonzero** [comment] 2019-05-16 20:52
I'm not sure why you would, my point is more that we aren't trying to rigorously exclude them, we are just ignoring them and thus their type is basically meaningless, unfortunately GHC/Haskell doesn't have a notion of "completely irrelevant type variables" so we need to give it some concrete type. I'd be fine with `Void` also, just anything that allows me to do concise inline parsing without extensions would be fantastic.
