### ISSUE TITLE
A possible regression regarding error reporting

### ISSUE THREAD

**Issue by neongreen** [mrkkrp/megaparsec#35] opened 2015-09-21 17:44 UTC
Here's a Parsec parser:

~~~ haskell
import Text.Parsec
import Text.Parsec.Language
import Text.Parsec.Lexer

decimal' = decimal (makeTokenParser haskellDef)

pair = do
  char '{'      <?> "opening brace"
  a <- decimal' <?> "1st number"
  char ','      <?> "comma"
  b <- decimal' <?> "2nd number"
  char '}'      <?> "closing brace"
  eof
  return (a, b)
~~~

It gives the following errors on various inputs:

~~~
> pair "{1a,456}"
*** Exception: (line 1, column 3):
unexpected "a"
expecting digit or comma

> pair "{a,456}"
*** Exception: (line 1, column 2):
unexpected "a"
expecting 1st number
~~~

Here's an equivalent Megaparsec parser:

~~~ haskell
import Text.Megaparsec
import Text.Megaparsec.Lexer

pair = do
  char '{'     <?> "opening brace"
  a <- decimal <?> "1st number"
  char ','     <?> "comma"
  b <- decimal <?> "2nd number"
  char '}'     <?> "closing brace"
  eof
  return (a, b)
~~~

And its errors:

~~~
> pair "{1a,456}"
*** Exception: line 1, column 3:
unexpected 'a'
expecting 1st number or comma

> pair "{a,456}"
*** Exception: line 1, column 2:
unexpected 'a'
expecting 1st number
~~~

Parsec's error when parsing `{1a,456}` seems more helpful to me (it would be even more apparent if instead of `decimal` there was a more complicated parser). Am I mistaken?

**Comment by mrkkrp** [comment] 2015-09-21 17:59
@neongreen, Well, I wouldn't call it “regression”. First of all I have to state clearly that this is expected behavior and I know about it. Call it a feature if you like.

I do understand your reaction and Megaparsec's error message may be a bit incorrect. What it actually should say is:

```haskell
> pair "{1a,456}"
*** Exception: line 1, column 3:
unexpected 'a'
expecting rest of 1st number or comma
```

“Rest of” is meant. I can explain why this happens. There are two features which both are quite good for error reporting but their combination in this particular case produces rather strange report (oh, not perfect would be better phrase).

1. When you're using `many` and at some point its argument parser fails its message get into hints. So, after parsing `1` we have hints like `[["digit"]]`. This is necessary because when something fails right after `many` combinator we can say that actually `"digit"` could follow here too (*or* what failed combinator expected).

2. `label` is applied on combinator which has hints. Most recent block of hints `["digit"]` is replaced with text of label `["1st number"]`.

Combination of these features result in this sort of message. This is not impossible to actually prepend the prefix `"rest of "` to hint produced by `label` in some cases. Thanks for this info, I'll see if I can fix it in decent manner.

**Comment by tulcod** [comment] 2015-09-21 18:01
How about reporting `unexpected "1a", expecting 1st number` instead? After all, the label is on all of "decimal", not on whatever remaining part of it doesn't parse.

**Comment by neongreen** [comment] 2015-09-21 18:03
@tulcod, what should happen when instead of “1a” there's 20kB of JSON (because what I'm parsing is, say, `(JSON, JSON)` and not `(Integer, Integer)`)? Should it put it all in error message, or truncate it, or something else?

**Comment by tulcod** [comment] 2015-09-21 18:07
@neongreen, that can also happen when you're expecting a very long fixed string (e.g. a header, or the repetition of a previous block - nothing unrealistic IMO). so that is already a problem. if you want to deal with that, I guess you could truncate "expected" and "expecting" strings in the error output, which might help with performance sometimes but will cost some performance at other times.

**Comment by mrkkrp** [comment] 2015-09-21 18:15
@tulcod, apart from the fact that `many` could have parsed really *many* things before failing, this would be not trivial to implement.

We can do, and we do this sort of reporting for `tokens` parser because its use case is more limited and the whole thing happens inside one primitive parser.

Here we would need to connect `many` and any following parser that fails. This is because `many` doesn't fail when it encounters something its argument parser cannot parse, it just stops there. The only available information at this point is collection of hints that tells us what sort of thing its argument parser wanted. `many` itself succeeds and next parser after it fails. At this point it is impossible (without redesigning of low-level Megaparsec workings) to tell what `many p` has parsed before. We only know what `p` wanted, what currently failed parser expected and what was actually encountered. From these pieces it's impossible to construct error message like that that `tokens` produces.

**Comment by mrkkrp** [comment] 2015-09-21 18:17
@tulcod, yes this may be a problem if you want to parse long string exactly. In this case you can simply:

```haskell
string "my long string" <?> "my…"
```

**Comment by mrkkrp** [comment] 2015-09-21 18:23
@tulcod, You can always use `hidden` on any parser and it will “hide” it from error messages completely.

**Comment by neongreen** [comment] 2015-09-21 18:51
> Most recent block of hints `["digit"]` is replaced with text of label `["1st number"]`

On one hand, this is wrong – we are throwing away lots of useful context that could help the user find what the error is. Having a stack of hints would be better.

On the other hand, a disclaimer: I don't know how to fix it and the “stack of hints” idea seems to be a minefield. If you have a recursively defined structure and it's 15 levels deep, you probably don't want to report errors in it like *this*, after all:

~~~
error while parsing an object:
error while parsing an array:
error while parsing an object:
error while parsing an array:
...
error while parsing 1st component of a pair:
error while parsing an object:
error while parsing an object:
expected double quote, found 'a'
~~~

On the other hand, if you're parsing `(ArithExpr, ArithExpr)` instead of `(Integer, Integer)`, you don't want to be getting errors like “expected expression” when you miss a paren, you want to actually know where in the expression you missed it. At the same time, when there was no consumed input yet, you would be satisfied with “expected arithmetic expression, found a string” – a list of all possible tokens that can start an expression would be of little use.

Is there any prior art in the area of “good parser error reporting”?

**Comment by mrkkrp** [comment] 2015-09-21 19:00
A lot of things depends on programmer who write parser. It's his responsibility to “get it right”. You won't get “expecting expression” error in Megaparsec if you miss a parenthesis if you have something like:

```haskell
expr :: MonadParsec s m Char => m Node
expr = makeExprParser term table <?> "expression"

term :: MonadParsec s m Char => m Node
term = parens expr <|> (Val <$> integer) <?> "term"
```

try it. You will most likely get “unexpected end of input, expecting ")"”. So, in a sense you're overcomplicating this.

**Comment by mrkkrp** [comment] 2015-09-21 19:04
> On one hand, this is wrong – we are throwing away lots of useful context that could help the user find what the error is.

Not really, it just replaces most recent collection of hints. That's how labels work by definition. And hints don't accumulate or nest or something, they actually “expire” when next parser doesn't fail without consuming input or doesn't succeed without consuming input. So, hints are quite volatile.

**Comment by mrkkrp** [comment] 2015-09-21 19:22
Also please note that this issue is only possible with `many` (or `some`). This is the only case when this can happen. When you have compound parsers instead, they will be reported using label only when they don't consume any input (fail without consuming or succeed without consuming and next parser immediately fails). This "feature" is only apparent when `many` is labelled.

**Comment by neongreen** [comment] 2015-09-21 19:24
> This "feature" is only apparent when `many` is labelled.

Ahh. Okay, I see.

**Comment by mrkkrp** [comment] 2015-09-21 19:31
"Unfortunately" `many` can consume input, succeed, and produce hints at the same time :-) I don't really see how this can be easily corrected.

**Comment by mrkkrp** [comment] 2015-09-21 19:37
One method is to have a wrapper that would indicate that particular set of hints is produced by `many` or not. Then in `label` we can prepend “rest of” to label before putting it in place of original hints.

Another idea is to have a wrapper that would tell if particular collection of hits can be replaced by `label`. Then `many` could wrap the hints accordingly (when no input consumed, use `Replace` wrapper, otherwise `DontReplace`, for example, names of wrappers can be better).

**Comment by mrkkrp** [comment] 2015-09-21 19:43
Somehow Parsec handles this better. Well, it works worse in other cases (maybe it's all interconnected). At any rate I cannot easily reason about how Parsec works in details but as you can see I currently can tell exactly why Megaparsec producing this or that result :-)

I think this idea with wrappers that can limit powers of `label` is the clearest one. I don't know if this could cause any slowdown given that hints don't accumulate or live long. In most cases there will be no difference.

**Comment by mrkkrp** [comment] 2015-09-21 20:53
No this doesn't quite work. Actual thing used here is `some` which consumes one element and then calls `many`. So since `many` cannot know anything about previously parsed things, even if it's smart enough to fail on empty input with "overwritable" hints, you still get the same situation. Let's see why Parsec is so smart in this case. What's some special about it...

**Comment by mrkkrp** [comment] 2015-09-21 21:01
Oh, I'm ready to call it a feature and mark it "wontfix". After all Megaparsec is right: 'a' is unexpected and you better give it more of 1 st number, so 1 st is expected. It's not that illogical after all.

**Comment by neongreen** [comment] 2015-09-21 21:04
> Actual thing used here is `some` which consumes one element and then calls `many`.

Could `some` be rewritten not to use `many`?

**Comment by neongreen** [comment] 2015-09-21 21:06
Actually, perhaps it should be done anyway, because otherwise

~~~ haskell
manyErr :: a
manyErr = error
    "Text.Megaparsec.Prim.many: combinator 'many' is applied to a parser \
    \that accepts an empty string."
~~~

becomes misleading when the user wrote `some` and not `many`. Hm?

**Comment by neongreen** [comment] 2015-09-21 21:09
> It's not that unlogical after all.

Yep, but it still leads to rather confusing messages. In the `expr` example, for instance:

~~~ haskell
λ> parseTest expr "(1"
parse error at line 1, column 3:
unexpected end of input
expecting ')' or expression
~~~

Here it's completely unclear whether “expression” means “rest of expression” or “expression token” (i.e. whether it would be right to continue `(1` with e.g. `(2)`).

**Comment by mrkkrp** [comment] 2015-09-21 21:10
@neongreen, yes but I don't currently think `some` deserves non-intuitive ad-hoc definition. Please understand me correctly, if it could be fixed by rewritting `some` I would just rewrite it. But I want to preserve consistency and common sense. Common sense tells me that `some` should not be different from `(:) <$> p <*> many p`. I would better live with this harmless feature than introduce ad-hoc logic in basic things.

Well, this sort of message is hardly intended to be seen by user of result software, it's rather for programmer so he doesn't forget that he cannot feed parsers of this sort to `many` (and thus `some`).

**Comment by mrkkrp** [comment] 2015-09-21 21:21
That definition is flawed. If I remove `<?> "expression"` I get:

```haskell
λ> parseTest (expr <* eof) "(1"
parse error at line 1, column 3:
unexpected end of input
expecting ')', operator, or term
```

Which is better, but the same issue arises with `term` (previously every `term` was `expression`, so Megaparsec's logic is correct). If you can propose good way to fix it I'm ready to consider it.

**Comment by mrkkrp** [comment] 2015-09-21 21:30
I will return to this later. Right now I cannot come up with anything.

**Comment by mrkkrp** [comment] 2015-09-21 21:41
Yeah, for the library that should have best error messages in Haskell world this is definitely not comme il faut.

**Closed** 2015-09-22 09:22 UTC
Labels: bug, discussion

**Comment by mrkkrp** [comment] 2015-09-22 09:25
@neongreen, @tulcod, this is resolved now, see commit message for explanation. I was a bit sleepy when @neongreen reported this, so this solution didn't come to my mind.
