### ISSUE TITLE
Natural Transformation of Stream Type

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mrkkrp/megaparsec#378] opened 2019-10-21 20:07 UTC
I am having trouble figuring out how to transform the stream type of one parser to another.

I am reading my file as a `ByteString` but the file has a structure that makes sense to have a custom Stream of `Token s = (Word16, ByteString)` like:
```dxf
0
SECTION
1
1.234
0
ENDSEC
0
EOF
```
I still need a parser for the custom stream type and would like to keep the line numbers from the file associated with new stream. Is this possible to `Parsec Void [(GroupCode, ByteString)] ~> Parsec Void ByteString`?

**Comment by mrkkrp** [comment] 2019-10-21 20:52
There is no official way to do it (you probably can invent something, but then you're exploring a lonely dangerous path with no guarantees).

What I'd do here, I'd just write `Parsec Void ByteString MyResult` parser right from the ground up using the existing `Lexer` modules. The `(Word16, ByteString)` idea is simply not worth it in this case.

In beginning of November I'll be working one week full time on version 8 of the library and the main goal is to make working with custom input streams ~~great again~~ easier. See #345 for example of problems the users have reported. So if you really want the custom stream experience, be my guest I can ping you so you can be an early tester.

**Comment by BebeSparkelSparkel** [comment] 2019-10-21 20:59
Do you have a list of objectives for November?

**Comment by mrkkrp** [comment] 2019-10-21 21:01
Yes, you can see it here: https://github.com/mrkkrp/megaparsec/projects/1.

**Comment by BebeSparkelSparkel** [comment] 2019-10-22 06:36
Thank you for the offer to be an early tester but I do not think I have enough experience to be of much help to you. However, I will be watching megaparsec for releases and will try it out.

**Comment by mrkkrp** [comment] 2019-10-22 13:21
I'm going to close this one as a sort of duplicate of #345 then.

**Closed by mrkkrp** 2019-10-22 13:21 UTC
Labels: question
