### ISSUE TITLE
Difficulty making a `Stream` instance in certain cases

### ISSUE THREAD

**Issue by seagreen** [mrkkrp/megaparsec#345] opened 2019-03-17 18:16 UTC
### Problem

I'm trying to use [lexer-applicative](https://hackage.haskell.org/package/lexer-applicative) for lexing and `megaparsec` for parsing, similar to the use described in [this old issue](https://github.com/mrkkrp/megaparsec/issues/120).

However, it's gotten harder to make a [Stream](http://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec-Stream.html#t:Stream) [[L](https://hackage.haskell.org/package/srcloc-0.5.1.2/docs/Data-Loc.html#t:L) token] instance since then.

The problem is that I'd like to be have the lexer throw away insignificant whitespace, but that means I can no longer recreate the source exactly which is required to implement [reachOffset](http://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec-Stream.html#v:reachOffset).

I considered keeping the original source around for use by `reachOffset`, eg:
```hs
data Lexed token = Lexed
  { originalSource :: Text
  , tokenStream :: [L token]
  }

instance Stream (Lexed token) where
  type Token (Lexed token) = L token
  type Tokens (Lexed token) = Lexed token
  ...
```
... but this runs into trouble when trying to implement [tokensToChunk](http://hackage.haskell.org/package/megaparsec-7.0.4/docs/Text-Megaparsec-Stream.html#v:tokensToChunk). There isn't a way to write `[L token] -> Lexed token` because the value to use for `originalSource` isn't known.

## Analysis

I don't see this as an urgent problem. My guess is that using a separate lexer and parser is slower than using megaparsec alone, and I'm only doing it in this project for educational purposes.

However, it is the traditional way of doing things, and if we can think of a way to support it without major changes that would be cool.

**Comment by banacorn** [comment] 2019-04-03 09:51
I agree with OP.

One of the selling point of Megaparsec is that, we can handle token streams other than those "strings".
But methods like `reachOffset` is making it really really difficult to do so.

Also, people using lexers like [lexer-applicative](https://hackage.haskell.org/package/lexer-applicative) usually have very good source location information covered. Perhaps we could add an alternative to `reachOffset` for those who already have locations in hand to report it?

**Comment by mrkkrp** [comment] 2019-07-19 19:11
I'm adding it to the list of things I'll be thinking about when designing changes for version 8.

**Comment by JKTKops** [comment] 2019-07-23 20:15
On a related note, there's no way to tell `MegaParsec` how to update position information in a custom stream short of wrapping the parser in a newtype and re-implementing the `MonadParser` class. This leads to unexpected behavior (because the implementation of `reachOffset` does require calculating new position information!) like linefolds failing because the internal position is always `1:1`.

**Comment by mrkkrp** [comment] 2019-10-26 17:54
@seagreen If we found a way to drop `tokensToChunk` so that you don't have to implement it for your custom stream, would it solve the problem? I imagine if you keep span information around and then use that in `reachOffset` it should work fine?

I think we only have `tokensToChunk` to be able to implement `crlf` in `Text.Megaparsec.Char` and `Text.Megaparsec.Byte`. The motivation is that you want to parse a `chunk` of input and return something of type `Tokens s` but then you need to provide the chunk to match against and the combinator should work for basically two types of input: lazy and strict for `Token s ~ Char` (three in this case because `String` also satisfies the constraint) and `Token s ~ Word8`. This is why we cannot just pass a literal there, we take a `String` which is `[Char]` and then apply `tokensToChunk` to get `Tokens s`.

As I started thinking about this, an alternative formulation came to my mind, in terms of the `IsString` type class:

```haskell
crlf ::
  forall e s m.
  (MonadParsec e s m, Token s ~ Char, IsString (Tokens s)) =>
  m (Tokens s)
crlf = string (fromString "\r\n")
```

Given that the stock lexer modules are not to be used with custom input streams anyway, it looks acceptable.

@banacorn I do not understand why `reachOffset` is problematic if you have source span positions. As @seagreen shows in the snippet above, you could just use the span info to get positions and then return that from `reachOffset`. Do you see any problems with that approach?

@JKTKops If you have a custom input stream, you can define how to update position information by implementing `reachOffset` when you make your stream type instance of `Stream` and that should be enough. I do not see why you would need to re-implement `MonadParsec`. Can you clarify?

**Comment by JKTKops** [comment] 2019-10-26 19:16
My time has been consumed with schoolwork so my project has stalled, but my megaparsec module is [here](https://github.com/JKTKops/ProtoHaskell/blob/master/src/Compiler/Parser/MegaParser.hs). It looks like I did update position information in reachOffset - feel free to let me know if anything else looks wrong. All of the Megaparsec management is at the top of the module.

**Comment by mrkkrp** [comment] 2019-10-27 14:01
@seagreen Another question is whether or not `Tokens (Lexed token)` should be `Lexed token` and not `[L token]`.

**Comment by mrkkrp** [comment] 2019-10-27 14:12
I guess to get this one right I'll have to bite the bullet and write two non-trivial-enough parsers using external lexers: one using `lexer-applicative` and another one with `alex`.

**Comment by seagreen** [comment] 2019-10-29 21:18
> If we found a way to drop tokensToChunk so that you don't have to implement it for your custom stream, would it solve the problem? I imagine if you keep span information around and then use that in reachOffset it should work fine?

I believe so!

> Another question is whether or not Tokens (Lexed token) should be Lexed token and not [L token].

Not sure about this one.

**Comment by banacorn** [comment] 2019-10-30 03:27
> I guess to get this one right I'll have to bite the bullet and write two non-trivial-enough parsers using external lexers: one using `lexer-applicative` and another one with `alex`. This way'll figure out what's it's like.

Regardless of how things might change in megaparsec-8.0.0, this would be really helpful!!

**Comment by mrkkrp** [comment] 2019-10-30 10:43
> Not sure about this one.

I'd like to understand why. Because if we can use `[L token]` then the present definition of `Stream` is already OK and should work fine.

**Comment by seagreen** [comment] 2019-10-30 17:13
> I'd like to understand why. Because if we can use `[L token]` then the present definition of `Stream` is already OK and should work fine.

Aha, I see what you're saying. 

```hs
data Lexed token = Lexed
  { originalSource :: Text -- Used to implement `reachOffset`
  , tokenStream :: [L token]
  }

instance Stream (Lexed token) where
  type Token (Lexed token) = L token
  type Tokens (Lexed token) = [L token]
  -- ^ Using `[L token]` here instead of `Lexed tokens` means that
  -- the type signature of tokensToChunk is now:
  --
  --     Proxy s -> [Token s] -> Tokens s
  --
  -- which is just:
  --
  --     Proxy s -> [L token] -> [L token]
```

That solves this issue, thanks!

**Comment by mrkkrp** [comment] 2019-11-07 09:57
@seagreen Is your code available somewhere?

If the issue is solved, then things are not so bad and we can close this one perhaps?

**Comment by mrkkrp** [comment] 2019-11-07 18:31
I wrote a fully functional parser with custom input stream today. I took the parser from the official tutorial as starting point and made it display offending line properly. I'll publish the updated tutorial soon.

I think we can close this.

**Closed by mrkkrp** 2019-11-07 18:31 UTC
Labels: feature-request

**Comment by seagreen** [comment] 2019-11-07 18:33
Agreed with the decision to close this, your `type Tokens (Lexed token) = [token]` idea means `megaparsec` doesn't need to change :ok_hand:
